version: '3'
services:
    app:
        hostname: my_docker_app
        build:
            context: app
            dockerfile: dockerfile
        volumes:
            - ./app:/app
        ports:
            - 5000:5000
        command: python3 /app/app.py
            # reverse_proxy:
            #     image: nginx

    db:
        hostname: my_docker_mongo
        image: mongo
        volumes:
            - ./db:/data/db
        ports:
            - 27017:27017
